/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.blockchain.insurance

import org.springframework.boot.SpringApplication
import org.springframework.boot.autoconfigure.SpringBootApplication

@SpringBootApplication(scanBasePackages = arrayOf("com.blockchain.insurance"))
class BlockChainInsuranceApp {

}
fun main(args: Array<String>) {
    SpringApplication.run(BlockChainInsuranceApp::class.java, *args)
}
